### ISSUE TITLE
MIlestone 1 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci_532_group_24#19]
Hi Group 24,

- great overall concept! The example with Aiden and his journey and need for your app was well done. 
- At first glance your app looks very simple. However I can see with the descriptions that there are a lot of interactive pieces. 
- I’m wondering how visible the text will be with all countries displayed in the bar graph on the left. And if you will add a hover or click option to the map.
- The right bar plot doesn’t quite fit with your desired flow. I think it should match with the country selected on the left and show all the diseases or if it should only show the rates for a specific disease for each country and be ordered in the same order as the bar plot on the right. Currently the sketch shows both bar plots ordered from highest to lowest. The right plot could also be changed to show all diseases as a proportion in a stacked bar graph to help someone do a lot of comparisons quickly
- Ideally if someone hovered over a country on the map they would see the name of the country, total mortality rate, and if space the rate for each of the diseases with number and percent for extra clarity.
- As the user I am also wanting to see a line plot to show trends for countries, and not just info for one year.
- Where will you have a legend for the map?

**Comment by ZIBOWANGKANGYU** [comment]
Thank you, Analise! We will make improvements as you suggest, this week and in the following weeks.

**Comment by jkim222383** [comment]
- [x] Make sure text is visible in the left countries bar graph: Limited number of countries displayed in barchart https://github.com/UBC-MDS/dsci_532_group_24/pull/13, updated with https://github.com/UBC-MDS/dsci_532_group_24/pull/29
- [x] Make the right bar chart functionality more clear: Right bar chart also depends on the countries and diseases selected. Interactive components were grouped together in a panel and description was added to make it more clear that the controls as a group influence both bar charts + map. No longer needs to be a stacked bar chart since visualization would be difficult with 5+ countries for each disease type https://github.com/UBC-MDS/dsci_532_group_24/pull/33
- [x] Mouse-over for map shows country and mortality figures (raw count or per 1000 children depending on option chosen) https://github.com/UBC-MDS/dsci_532_group_24/pull/18, updated with https://github.com/UBC-MDS/dsci_532_group_24/pull/33 . [ ] Mouse-overs for bar charts show stats related to each disease and country https://github.com/UBC-MDS/dsci_532_group_24/pull/13. Individual country/disease statistics can be found by limiting the selected disease/country to only one disease/country.
- [x] Trends tab added in https://github.com/UBC-MDS/dsci_532_group_24/pull/30 to show trends for countries over multiple years
- [x] Add legend for the map: Legend for color scale added in https://github.com/UBC-MDS/dsci_532_group_24/pull/23
